version: 0.1
phases:
 install:
   commands:
     - echo "install step"
 build:
   commands:
     - npm install
     - gulp
 post_build:
   commands:
     - aws s3 sync --delete . "s3://<your-static-website-bucket>"