version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 build:
   commands:
     - npm install
 post_build:
   commands:
     - rm -rf node_modules
     - rm -rf bower_components
     - aws s3 sync --delete . "s3://aws-website-devalexwattocouk-wca6c"
artifacts:
  files: 
    - '/public/*'
  base-directory: 'public*'
  discard-paths: yes