version: 0.1
phases:
 install:
   commands:
     - echo "install step"
 build:
   commands:
     - npm install -g
     - gulp default
 post_build:
   commands:
     - aws s3 sync --delete . "s3://aws-website-wwwalexwattocouk-nxpfu"