version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 build:
   commands:
     - npm install
     - gulp default
 post_build:
   commands:
     - rm -rf node_modules
     - rm -rf bower_components
     - aws s3 sync --delete . "s3://aws-website-wwwalexwattocouk-nxpfu"
artifacts:
 files:
   - public/*
 discard-paths: yes