version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 build:
   commands:
     - npm install
 post_build:
   commands:
     - aws s3 sync public/ s3://aws-website-devalexwattocouk-wca6c
artifacts:
  files: 
   - 'public/index.html'
